version: '3'

services:
  server:
    build:
      context: ./server
      args:
        UID: ${UID}
        GID: ${GID}
        SERVER_ROOT_PASSWORD: ${SERVER_ROOT_PASSWORD}
    container_name: server
    ports:
      - 80:80
      - "2200:22"
    volumes:
      - ./data/www:/home/serveruser/vhosts
    links:
      - db
      - db2
    networks:
      app_net:
        ipv4_address: 10.100.100.11
  db:
    image: mariadb
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./db/config:/etc/mysql/conf.d:delegated
    environment:
      TZ: "Europe/Athens"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      app_net:
        ipv4_address: 10.100.100.21
  db2:
    image: mariadb
    container_name: db2
    ports:
      - 3307:3306
    volumes:
      - db2-data:/var/lib/mysql
      - ./db2/config:/etc/mysql/conf.d:delegated
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      app_net:
        ipv4_address: 10.100.100.31
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOSTS: db,db2
      PHP_UPLOAD_MAX_FILESIZE: 67108864
    networks:
      app_net:
        ipv4_address: 10.100.100.41
  redis:
    image: redis:3.2
    volumes:
      - redis-data:/data
    networks:
      app_net:
        ipv4_address: 10.100.100.51
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.100.100.0/24
volumes:
  db-data:
  db2-data:
  redis-data:
